-- 订单配置表
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('orderCreateClub', 'orderCreateClub', '0.1', '{\"defId\":\"1\",\"dbId\":\"0001\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"003\",\"partitionNum\":\"1\"}', '1', '3', '3');
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('coojisu_playing', 'coojisu_playing', '1.0', '{\"defId\":\"2\",\"dbId\":\"0002\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"005\",\"partitionNum\":\"5\"}', '1', '3', '3');
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('orderCreateRoom', 'orderCreateRoom', '0.1', '{\"defId\":\"1\",\"dbId\":\"0001\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"003\",\"partitionNum\":\"1\"}', '1', '3', '3');
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('bal_reduce_game', 'bal_reduce_game', '0.1', '{\"defId\":\"1\",\"dbId\":\"0001\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"006\",\"partitionNum\":\"1\"}', '1', '3', '3');
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('recharge_userDiamondAcc', 'recharge_userDiamondAcc', '0.1', '{\"defId\":\"1\",\"dbId\":\"0001\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"003\",\"partitionNum\":\"1\"}', '1', '3', '3');
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('bal_reduce_club_to_room', 'bal_reduce_club_to_room', '0.1', '{\"defId\":\"1\",\"dbId\":\"0001\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"006\",\"partitionNum\":\"1\"}', '1', '3', '3');
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('bal_reduce_room_to_club', 'bal_reduce_room_to_club', '0.1', '{\"defId\":\"1\",\"dbId\":\"0001\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"006\",\"partitionNum\":\"1\"}', '1', '3', '3');
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('category_modifyUser', 'category_modifyUser', '0.1', '{\"defId\":\"1\",\"dbId\":\"0001\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"103\",\"partitionNum\":\"1\"}', '1', '3', '3');
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('balTransfer', 'balTransfer', '0.1', '{\"defId\":\"1\",\"dbId\":\"0001\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"006\",\"partitionNum\":\"1\"}', '1', '3', '3');
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('balTransferSysToUnion', 'balTransferSysToUnion', '0.1', '{\"defId\":\"1\",\"dbId\":\"0001\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"006\",\"partitionNum\":\"1\"}', '1', '3', '3');
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('balTransferUnionToSys', 'balTransferUnionToSys', '0.1', '{\"defId\":\"1\",\"dbId\":\"0001\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"006\",\"partitionNum\":\"1\"}', '1', '3', '3');
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('category_modifyClub', 'category_modifyClub', '0.1', '{\"defId\":\"1\",\"dbId\":\"0001\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"103\",\"partitionNum\":\"1\"}', '1', '3', '3');
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('login', 'login', '0.1', '{\"defId\":\"1\",\"dbId\":\"0001\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"103\",\"partitionNum\":\"1\"}', '1', '3', '3');
INSERT INTO `user_dbcloud`.`order_flow_def`(`catetory`, `category_name`, `version`, `orderId_category`, `deploy_id`, `steps`, `finished_step`) VALUES ('gmaeSession', 'gmaeSession', '0.1', '{\"defId\":\"1\",\"dbId\":\"0001\",\"dbIdLength\":\"4\",\"partitionIdLength\":\"3\",\"partitionStartId\":\"103\",\"partitionNum\":\"1\"}', '1', '3', '3');
